### ISSUE TITLE
A point of interest

### ISSUE THREAD

**Issue by Sebbyastian** [CProgrammingFBGroup/CProgrammingNotes#1]
It might pay to note the attention in the detail here.

> You may use int main( void ) or int main() if you don't want your program to be able to accept and process command line arguments.

The difference between these two is subtle but significant, in that an implementation may require the `(void)` to explicitly specify no arguments, where-as `int main()` specifies an indeterminate number of arguments of indeterminate type. See for yourself:

    int main() {
        return main("Man... This is so unconventional", 42.0, &main);
    }

Since this doesn't actually declare a prototype for the function, I could reasonably see an implementation getting confused about which prototype to use, perhaps pushing some things to the stack which aren't meant to be pushed... Pass no arguments, or pass two arguments, or pass three (there's often an `envp` extension in Unix)? How does the linker decide? I suppose they could write logic to build that kind of expensive analysis into the linker, but the better option is to avoid the undefined behaviour.

So what is `()` good for, then? You'll notice most compilers won't even warn you when arguments are completely invalid... This [works on ideone](https://ideone.com/UQER7b)... as in, it compiles and runs...

    unsigned int fubar();
    int main(void) {
         fubar("hello", "world");
    }
    unsigned int fubar(unsigned int x, unsigned int y, unsigned int z) {
         return x ^ y ^ z;
    }

Try it with `(void)` on the other hand and you'll most likely get compiler error after compiler error telling you not everything is so peachy! Using `()` fundamentally breaks all type checking in C, as though there was enough to begin with... They're not the same thing, that's for sure!

**Comment by Trenix25** [comment]
Please have a look at lessons/defining_main_lesson.txt.

/Matthew Campbell

**Comment by Sebbyastian** [comment]
What else do you think I'm commenting on? This kind of stuff here...

> The main() function _must_ return an integer value in every case

More specifically, `main` must return `int`, not just _an integer_.

> You may use int main( void ) or int main()

... and I've already pointed out what's wrong with `int main()`... if there are any words there which you don't understand, why not ask about them rather than suggest I review this document which you haven't yet fixed?

> you should add the following command line options when compiling your
programs: -pedantic -std=c11 -Wall if they are not already specified.

Curious if you add `-Wstrict-prototypes` to that, what do you get, hmmm? Try it... I did.
```

Owner@Core MINGW64 ~
$ cat strict_prototype_test.c
int main() { }

Owner@Core MINGW64 ~
$ gcc -pedantic -std=c11 -Wall -Wstrict-prototypes strict_prototype_test.c
strict_prototype_test.c:1:5: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 int main() { }
     ^~~~

```

Not sure if you want your students to run into undefined behaviour and unstable issues with portability, but you know, it's best to be safe than sorry... right?

**Comment by Trenix25** [comment]
When I said integer I was merely spelling out the name of the data type in plain language.  No need to get so worked up over it.  I didn't specifically add any warning for strict prototypes and my code compiles just fine.  main() isn't normally prototyped anyway.

/Matthew Campbell

**Comment by Sebbyastian** [comment]
> When I said integer I was merely spelling out the name of the data type in plain language.

Do you go by the standard? I mean... the standard says there are a few standard integer types... which one are you referring to? I presume `int`. You don't mean to say `main` returns `long` or `long long`, right? Because both of those are technically also integer types... then you've got the unsigned types, and `size_t`... `main` doesn't typically return `size_t`, right? That's an integer...

> It may be worth pointing out that your main() function in your example did not do or return anything.

Please refer to [C11/5.1.2.2.3p1 Program Termination](https://port70.net/~nsz/c/c11/n1570.html#5.1.2.2.3p1) for further details on what my program does. Here it is quoted, with some important bits emphasized in bold (by me) for your convenience:

> If the return type of the main function is a type compatible with int, a return from the initial call to the main function is equivalent to calling the exit function with the value returned by the main function as its argument;11) **reaching the } that terminates the main function returns a value of 0.**

**Comment by Trenix25** [comment]
In your example about main(), those comma separated constants will likely be ignored and the address of the main() function will be returned to the operating system as the process' exit code.

/Matthew Campbell

**Comment by Sebbyastian** [comment]
My main point is to show you the devil in what you're doing. Beyond that, I don't really care what you do with that insight. Risk four hours hunting for some portability bug caused by four missing keystrokes for all I care... that only affects you, unless you try to teach others.

> the address of the main() function will be returned to the operating system

Care to take another shot at that? The `main` function is invoking itself recursively. Supposing it ever returns, its return value (which has type `int`) is returned, not a function pointer. To return that function pointer I would have to sans the invocation and write `return main;`.

> those comma separated constants

The arguments, you mean? Are there zero, one, or many arguments there? `int main() { }` declares a function with an indeterminate number of arguments of indeterminate type (as evidenced by the fact that you can call it with any number of argument of any type), and a linker can't see your source code, so do you suppose a linker will always know how to call it? Or might this be another one of those potential portability traps?
