### ISSUE TITLE
An important note on strings

### ISSUE THREAD

**Issue by Sebbyastian** [CProgrammingFBGroup/CProgrammingNotes#2]
I see this often. Strings are described as though they're something complex being explained in a simple way because we've had troubles understanding them as they are. The problem is compounded by some other features that go hand in hand. Don't treat your audience like that. You know, if you always teach things one way you can't know the value of teaching them another.

Assuming that we're on the same page, [here's a quote from the C standard](https://port70.net/~nsz/c/c11/n1570.html#7.1.1p1), broken into easier to digest segments, though it's all provided as a blob with some other crap (we'll get to that) in the standard:

> The length of a string is the number of bytes preceding the null character

Can you see any reason why you can't just tell someone this and expect them to understand it? Yet the "length" of an array... the closest thing is the `sizeof` an array, and that's a different value, right? Speaking of values...

> the value of a string is the sequence of the values of the contained characters, in order.

In other words, the value is most likely _not_ a pointer. The C standard also defines the term _value_ in a broader sense, so it can be applied to arrays, integers, floating points, you know, the data types of C more generally...

> precise meaning of the contents of an object when interpreted as having a specific type

The type is character array of unspecified size, the value is the "precise meaning of the contents" of the array. We can choose to store multiple string values into the space we've been given. For example:

    char str[] = "string literal";
    printf("%d\n", strcmp(str, str + 1));

Here you can see `strcmp` compare two different strings that occupy the same array, and `strcmp` says they're different strings! Fancy that! ¯\_(ツ)_/¯

In fact I could use any of the string operations on them, providing I don't cause UB, you know, the usual precautions...

This does not fit with the description of a string as an array of characters ending in `'\0'`, as one of these strings does not fully occupy the array. Strings can exist at the beginning of arrays, in the middle of arrays, with uninitialised garbage _between the null byte and the end of the array_, etc... Were you referring to _string literals_, perhaps? Because in that case, you're not too far off; compilers often end up transforming string literals into an arrays in some region of generally assumed non-modifiable memory... and those arrays are usually precisely sized to store the contents of the non-modifiable string, including the null terminator right at the end as per your definition. However, I want to put more than 12 eggs into an egg carton...

    #include <stdio.h>
    int main(void) {
        char eggs[12] = "string literal";
        fwrite(eggs, sizeof *eggs, sizeof eggs / sizeof *eggs, stdout);
        fflush(stdout);
    }

[Tada](https://ideone.com/r5Sr6M)! You've won a "string liter" (and possibly some garbage)! In this case, it turns out the string literal might not be used to generate an array that contains a null byte... so this string literal would turn out not to be converted to a string.

> An array of character type may be initialized by a character string literal or UTF-8 string literal, optionally enclosed in braces. Successive bytes of the string literal (including the terminating null character if there is room or if the array is of unknown size) initialize the elements of the array.

-- [6.7.9p14](https://port70.net/~nsz/c/c11/n1570.html#6.7.9p14)

Praise thy builder.

> A pointer to a string is a pointer to its initial (lowest addressed) character

This is what we end up passing to our string functions. When we read `strlen("Hello world");` we don't see the variable declaration that is in the argument list for the function. That looks something like: `size_t strlen(char const *fubar);`... So behind the scenes there is a conversion occurring from string literal to character array, then from character array to character pointer. We can see this in the documentation...

>        #include <string.h>
>        size_t strlen(const char *s);
>
> Description
> 
> The strlen function computes the length of the *string pointed to by s*.

Okay, I predicted `char const`. The standard uses `const char`. Same, different, whatever. These implicit conversions, from string literal to character array, and then from character array to pointer, are what people struggle with, and they're the keys to understanding string literal vs array vs string and how it all connects.

> Except when it is the operand of the sizeof operator, the _Alignof operator, or the unary & operator, or is a string literal used to initialize an array, *an expression that has type ''array of type'' is converted to an expression with type ''pointer to type''* that points to the initial element of the array object and is not an lvalue. If the array object has register storage class, the behavior is undefined.

-- [6.3.2.1p3](https://port70.net/~nsz/c/c11/n1570.html#6.3.2.1p3)

I do hope we can lose this notion of "array decay", as I understand once the array has corroded, rotten, *decayed* then it might not be so useful to us...

**Comment by Trenix25** [comment]
A character string is simply an array of characters that ends with a null '\0' character.

/Matthew Campbell

**Comment by Sebbyastian** [comment]
I have no idea who the hell that is, but he doesn't decide what C is. The standards committee decides, and then the compiler developers follow the standards, so it's in your best interests as a programmer to also follow the standards.

> A string literal need not be a string (see 7.1.1), because a null character may be embedded in it by a \0 escape sequence.

-- [C11/footnote 78](https://port70.net/~nsz/c/c11/n1570.html#note78)

What this means is that string literals like `"hello\0world"` aren't actually strings. Whichever terminology you're using is not compliant in the world of C for this very reason. You need to listen closely, because it really can't get any simpler than what the standard makes it. There's no need to reinvent the definition. Here's how the standard words it (which is very different to how you word it):

> A string is a contiguous sequence of characters terminated by and including the first null character.

-- [C11/7.1.1p1](https://port70.net/~nsz/c/c11/n1570.html#7.1.1p1)

The sequence of characters needn't be in an array; it could be a single character (i.e. `char c; strcpy(&c, "");` and `c` now contains a string). It could be in a file. What matters is: sequence of characters... terminates at `'\0'`... if you've got those keywords, you're on the right track.

The array itself also doesn't need to end in `'\0'`... what matters is that there's a `'\0'` in the array. The string is the part of the array up until that terminator. To elaborate, the string is most likely NOT the entire array.

Do you understand correctly, yet? It is important to understand this correctly, because otherwise you look like a joke in the professional realm where they all follow standards...

**Comment by Trenix25** [comment]
My definition agrees with what you quoted from the standard.  An array is a contiguous block of memory that holds a series of memory locations used by the same data type.  A string is a collection of characters in a contiguous block of memory that ends with a terminating null character.  It was paraphrased which appears to have confused you.

/Matthew Campbell

**Comment by Sebbyastian** [comment]
The issue here, and an important one, is that the string doesn't necessarily occupy the entirety of the array. There are six strings in `"hello"`. `char c = '\0';` denotes initialisation of a valid string which you can obtain the length of by calling `strlen(&c);`. Both are points to establish along the lines of realising what a string is. `int x; strcpy((void *) &x, "");` is valid in the C standard, and performs an operation that copies a string into the place pointed at by `x`... yet `x` is not an array, right? The string only occupies a part of the array, not necessarily the whole lot, so you shouldn't be saying that it occupies the whole lot. This causes legitimate confusion in people learning... if you want to produce a good lesson, consider this stuff.
