### ISSUE TITLE
conditions_lesson.txt

### ISSUE THREAD

**Issue by Sebbyastian** [CProgrammingFBGroup/CProgrammingNotes#4]
Apologies if this seems nitpicky, but I assume you would want to correct mistakes and improve your content, because nobody is perfect and the more minds, the more mind power, etc... right?

The extra semicolon in `for( ;;; )` is absolutely an error, and I'll have you know that I pride myself in keeping a sharp eye on details... call it nitpicking if you like, it might often be more useful than you realise...

**Comment by Trenix25** [comment]
Thank you for pointing out my typo.  That has been fixed and the files have been updated.

/Matthew Campbell
