### ISSUE TITLE
Infinite loops in failure mode.

### ISSUE THREAD

**Issue by Sebbyastian** [CProgrammingFBGroup/CProgrammingNotes#5]
Often when input fails to read, we will want to display some error message to our end user and halt the program. `exit` is usually my tool of choice. I don't see anything in any of [this example code](https://github.com/CProgrammingFBGroup/CProgrammingNotes/blob/master/lessons/conditions_lesson.txt#L322), though... when that fails, it'll go into an infinite loop telling you that you've entered invalid input, when really what happened is you fed input from a file and the end of the file has been reached... something to note: end of file isn't always a *failure*... and we should probably write code more like:

```
for (;;) {
    switch (scanf("%d", &x)) {
        case EOF: /* for some failure other than a conversion failure, we usually terminate */
            exit(EXIT_FAILURE);
        case 0: /* for a conversion failure, we might read and discard a line of text and try again */
            scanf("%*[^\n]");
            continue;
        case 1: /* success */
    }
}
```

This allows you to handle `EOF` and other "physical" errors that might occur separately from typos like how a user might accidentally press a letter very near a number key when they're entering numeric data...

I mean, it might be okay if all you want is a wall of text that says "That is not an acceptable choice." when you want to bash script your programs... It's your choice. Take my advice with a grain of salt!

**Comment by Trenix25** [comment]
If this loop problem is occurring then a newline character is left in the input buffer and can be cleared with fgetc( stdin );.  This lesson was meant for beginners and as such it was not intended to address every possible condition that may potentially exist.  Using ^C also tends to work.

/Matthew Campbell

**Comment by Trenix25** [comment]
Fixed.

/Matthew Campbell

**Comment by Sebbyastian** [comment]
> If this loop problem is occurring then a newline character is left in the input buffer and can be cleared with fgetc( stdin );.

Wrong. The cause is when you close `stdin`. Less guessing and more reading (i.e. you can find out what `scanf` does to prefixed whitespaces by reading [the `fscanf` manual here](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fscanf.html)).

> This lesson was meant for beginners and as such it was not intended to address every possible condition that may potentially exist. Using ^C also tends to work.

The bug isn't caused by sending an interrupt signal to your program (i.e. `^C`); the bug is caused by closing `stdin`. You can typically use **`^d`** to close `stdin` in most traditional Unix-like OSes, or CTRL+Z in Windows.
